/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.applikasikesehatan;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.time.Duration;
import java.util.Scanner;
/**
 *
 * @author Asus
 */
public class Mainview extends javax.swing.JFrame {

    private float Field;

    /**
     * Creates new form Mainview
     */
    public Mainview() {
        this.berat = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cekaktivitasfisik = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cekpolamakan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cekpolatidur = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cekkesehatanumum = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        menuutama = new javax.swing.JPanel();
        panelpolamakan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        berapamakan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        makanankarbo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        makananprotein = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        makananvit = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        sarankonsumsi = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        kebutuhanprotein = new javax.swing.JButton();
        protein = new javax.swing.JTextField();
        panelpolatidur = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        awaltidur = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        awalbangun = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        hasilkurang = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        komentartidur = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        menitawaltidur = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        menitawalbangun = new javax.swing.JTextField();
        tidursiang = new javax.swing.JButton();
        tidaktidursiang = new javax.swing.JButton();
        panelumum = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        nadi = new javax.swing.JTextField();
        tombolcara = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        caramenghitung = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        sakittenggorokan = new javax.swing.JButton();
        hidungtersumbat = new javax.swing.JButton();
        nyeriotot = new javax.swing.JButton();
        sakitkepala = new javax.swing.JButton();
        sehatwalafiat = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        kondisi = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        okenadi = new javax.swing.JButton();
        panelkesehatanumum = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        GENDER = new javax.swing.JTextField();
        UMUR = new javax.swing.JTextField();
        tombolsehat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        komentarsehat = new javax.swing.JTextArea();
        panelaktivitasfisik = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        inputtinggibadan = new javax.swing.JTextField();
        inputberatbadan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        belumolahraga = new javax.swing.JButton();
        sudaholahraga = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        saranaktivitas = new javax.swing.JTextArea();
        tombolok = new javax.swing.JButton();
        hasilperhitunganbbideal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 48, 49));

        menupanel.setBackground(new java.awt.Color(255, 118, 117));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        home.setBackground(new java.awt.Color(204, 204, 204));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setText("HOME");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cekaktivitasfisik.setBackground(new java.awt.Color(204, 204, 204));
        cekaktivitasfisik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cekaktivitasfisikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cekaktivitasfisikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cekaktivitasfisikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cekaktivitasfisikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cekaktivitasfisikMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setText("CEK AKTIVITAS FISIK");

        javax.swing.GroupLayout cekaktivitasfisikLayout = new javax.swing.GroupLayout(cekaktivitasfisik);
        cekaktivitasfisik.setLayout(cekaktivitasfisikLayout);
        cekaktivitasfisikLayout.setHorizontalGroup(
            cekaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekaktivitasfisikLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cekaktivitasfisikLayout.setVerticalGroup(
            cekaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekaktivitasfisikLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cekpolamakan.setBackground(new java.awt.Color(204, 204, 204));
        cekpolamakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cekpolamakanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cekpolamakanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cekpolamakanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cekpolamakanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cekpolamakanMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setText("CEK POLA MAKAN");

        javax.swing.GroupLayout cekpolamakanLayout = new javax.swing.GroupLayout(cekpolamakan);
        cekpolamakan.setLayout(cekpolamakanLayout);
        cekpolamakanLayout.setHorizontalGroup(
            cekpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekpolamakanLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cekpolamakanLayout.setVerticalGroup(
            cekpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekpolamakanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cekpolatidur.setBackground(new java.awt.Color(204, 204, 204));
        cekpolatidur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cekpolatidurMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cekpolatidurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cekpolatidurMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cekpolatidurMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cekpolatidurMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setText("CEK POLA TIDUR");

        javax.swing.GroupLayout cekpolatidurLayout = new javax.swing.GroupLayout(cekpolatidur);
        cekpolatidur.setLayout(cekpolatidurLayout);
        cekpolatidurLayout.setHorizontalGroup(
            cekpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekpolatidurLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cekpolatidurLayout.setVerticalGroup(
            cekpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekpolatidurLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel8MouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel7.setText("LOG OUT");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(49, 49, 49))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cekkesehatanumum.setBackground(new java.awt.Color(204, 204, 204));
        cekkesehatanumum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cekkesehatanumumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cekkesehatanumumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cekkesehatanumumMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cekkesehatanumumMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cekkesehatanumumMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel15.setText("CEK KESEHATAN UMUM");

        javax.swing.GroupLayout cekkesehatanumumLayout = new javax.swing.GroupLayout(cekkesehatanumum);
        cekkesehatanumum.setLayout(cekkesehatanumumLayout);
        cekkesehatanumumLayout.setHorizontalGroup(
            cekkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cekkesehatanumumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(15, 15, 15))
        );
        cekkesehatanumumLayout.setVerticalGroup(
            cekkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cekkesehatanumumLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cekpolatidur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cekpolamakan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cekaktivitasfisik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cekkesehatanumum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekaktivitasfisik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekpolamakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekpolatidur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekkesehatanumum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuutama.setBackground(new java.awt.Color(255, 102, 102));
        menuutama.setLayout(new java.awt.CardLayout());

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel10.setText("CEK POLA MAKAN");

        jLabel24.setText("Berapa kali anda makan dalam sehari?");

        berapamakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berapamakanActionPerformed(evt);
            }
        });

        jLabel25.setText("Apakah anda mengonsumsi makanan berkarbohidrat? jika iya");

        makanankarbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan berkarbohidrat apa yang anda konsumsi?", "Nasi/Bubur", "Mie/Pasta", "Kentang/Ubi-ubian", "Roti/Oat/Sereal", "Jagung " }));
        makanankarbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanankarboActionPerformed(evt);
            }
        });

        jButton1.setText("Tidak");

        jLabel26.setText("Apakah anda mengonsumsi makanan berprotein? jika iya");

        makananprotein.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan berprotein apa yang anda konsumsi?", "Daging hewan ternak", "Telur", "Kedelai dan olahannya", "Susu dan olahannya", "Makanan Laut/Sungai" }));
        makananprotein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makananproteinActionPerformed(evt);
            }
        });

        jButton3.setText("Tidak");

        jLabel27.setText("Apakah anda mengonsumsi makanan/minuman bervitamin? jika iya");

        makananvit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan/Minuman apa yang anda konsumsi?", "Jeruk", "Alpukat", "Pisang", "kiwi", "bayam", "brokoli", "wortel", "tomat", "kacang almond", "kacang tanah", "kuaci", "susu", "yogurt", "keju", "ikan salmon", "ikan sarden", "teh hijau" }));
        makananvit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makananvitActionPerformed(evt);
            }
        });

        sarankonsumsi.setColumns(20);
        sarankonsumsi.setRows(5);
        jScrollPane4.setViewportView(sarankonsumsi);

        jLabel28.setText("Saran");

        jButton4.setText("Tidak");

        Ok.setText("Oke");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        kebutuhanprotein.setText("Berapa kebutuhan protein saya");
        kebutuhanprotein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebutuhanproteinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpolamakanLayout = new javax.swing.GroupLayout(panelpolamakan);
        panelpolamakan.setLayout(panelpolamakanLayout);
        panelpolamakanLayout.setHorizontalGroup(
            panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpolamakanLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28)
                    .addComponent(jScrollPane4)
                    .addGroup(panelpolamakanLayout.createSequentialGroup()
                        .addComponent(makananvit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpolamakanLayout.createSequentialGroup()
                        .addComponent(makananprotein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpolamakanLayout.createSequentialGroup()
                        .addComponent(makanankarbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpolamakanLayout.createSequentialGroup()
                        .addComponent(berapamakan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kebutuhanprotein)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(protein, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        panelpolamakanLayout.setVerticalGroup(
            panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpolamakanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(berapamakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ok)
                    .addComponent(kebutuhanprotein)
                    .addComponent(protein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makanankarbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makananprotein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpolamakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makananvit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        menuutama.add(panelpolamakan, "card4");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel11.setText("CEK POLA TIDUR");

        jLabel29.setText("Mulai jam berapa anda tidur pada malam hari?");

        awaltidur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awaltidurActionPerformed(evt);
            }
        });

        jLabel30.setText("Mulai jam berapa anda bangun pada pagi hari?");

        jLabel31.setText("Apakah anda tidur siang hari?");

        jLabel32.setText("Total jam tidur anda pada malam hari adalah :");

        komentartidur.setColumns(20);
        komentartidur.setRows(5);
        jScrollPane5.setViewportView(komentartidur);

        jLabel33.setText("Saran");

        jButton10.setText("Oke");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        menitawaltidur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menitawaltidurActionPerformed(evt);
            }
        });

        jLabel35.setText("Jam");

        jLabel36.setText("Menit");

        jLabel37.setText("Jam");

        jLabel38.setText("Menit");

        menitawalbangun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menitawalbangunActionPerformed(evt);
            }
        });

        tidursiang.setText("Iya");
        tidursiang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidursiangActionPerformed(evt);
            }
        });

        tidaktidursiang.setText("Tidak");
        tidaktidursiang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidaktidursiangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpolatidurLayout = new javax.swing.GroupLayout(panelpolatidur);
        panelpolatidur.setLayout(panelpolatidurLayout);
        panelpolatidurLayout.setHorizontalGroup(
            panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpolatidurLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpolatidurLayout.createSequentialGroup()
                        .addComponent(tidursiang)
                        .addGap(56, 56, 56)
                        .addComponent(tidaktidursiang))
                    .addComponent(jLabel33)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel11)
                    .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelpolatidurLayout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hasilkurang))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelpolatidurLayout.createSequentialGroup()
                            .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelpolatidurLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelpolatidurLayout.createSequentialGroup()
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(awalbangun, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel38)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(menitawalbangun, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelpolatidurLayout.createSequentialGroup()
                                            .addComponent(jLabel35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(awaltidur, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(menitawaltidur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpolatidurLayout.createSequentialGroup()
                                                    .addComponent(jLabel36)
                                                    .addGap(76, 76, 76)))))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton10)))
                    .addComponent(jLabel29))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        panelpolatidurLayout.setVerticalGroup(
            panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpolatidurLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(awaltidur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menitawaltidur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10)
                        .addComponent(menitawalbangun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38))
                    .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(awalbangun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(hasilkurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpolatidurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidursiang)
                    .addComponent(tidaktidursiang))
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        menuutama.add(panelpolatidur, "card5");

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel19.setText("CEK KESEHATAN UMUM");

        jLabel34.setText("Hitung denyut nadi anda dan isi pada kolom berikut");

        tombolcara.setText("Bagaimana cara menghitung denyut nadi?");
        tombolcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcaraActionPerformed(evt);
            }
        });

        caramenghitung.setColumns(20);
        caramenghitung.setRows(5);
        jScrollPane6.setViewportView(caramenghitung);

        jLabel6.setText("Apakah anda memiliki gejala seperti dibawah ini?");

        sakittenggorokan.setText("Sakit tenggorokan");
        sakittenggorokan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakittenggorokanActionPerformed(evt);
            }
        });

        hidungtersumbat.setText("Hidung tersumbat");
        hidungtersumbat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidungtersumbatActionPerformed(evt);
            }
        });

        nyeriotot.setText("Nyeri otot");
        nyeriotot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyeriototActionPerformed(evt);
            }
        });

        sakitkepala.setText("Sakit kepala");
        sakitkepala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakitkepalaActionPerformed(evt);
            }
        });

        sehatwalafiat.setText("Tidak ada satupun diatas");
        sehatwalafiat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehatwalafiatActionPerformed(evt);
            }
        });

        kondisi.setColumns(20);
        kondisi.setRows(5);
        jScrollPane7.setViewportView(kondisi);

        jLabel12.setText("Penjelasan");

        okenadi.setText("Oke");
        okenadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okenadiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelumumLayout = new javax.swing.GroupLayout(panelumum);
        panelumum.setLayout(panelumumLayout);
        panelumumLayout.setHorizontalGroup(
            panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelumumLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel34)
                        .addComponent(jLabel19)
                        .addGroup(panelumumLayout.createSequentialGroup()
                            .addComponent(nadi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(okenadi)
                            .addGap(7, 7, 7)
                            .addComponent(tombolcara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane6)
                        .addComponent(sehatwalafiat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelumumLayout.createSequentialGroup()
                            .addComponent(sakittenggorokan)
                            .addGap(12, 12, 12)
                            .addComponent(hidungtersumbat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nyeriotot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sakitkepala))
                        .addComponent(jScrollPane7)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        panelumumLayout.setVerticalGroup(
            panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelumumLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombolcara)
                        .addComponent(okenadi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sakittenggorokan)
                    .addComponent(hidungtersumbat)
                    .addComponent(nyeriotot)
                    .addComponent(sakitkepala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sehatwalafiat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        menuutama.add(panelumum, "card6");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setText("MENU UTAMA");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel13.setText("Masukkan gender anda");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel16.setText("Masukkan umur anda");

        jLabel17.setText("(Penulisan Huruf Kapital. contoh : LAKI-LAKI)");

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel18.setText("Apakah anda merasa sehat hari ini?");

        jButton2.setText("Sakit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENDERActionPerformed(evt);
            }
        });

        UMUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMURActionPerformed(evt);
            }
        });

        tombolsehat.setText("Sehat");
        tombolsehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsehatActionPerformed(evt);
            }
        });

        komentarsehat.setColumns(20);
        komentarsehat.setRows(5);
        jScrollPane2.setViewportView(komentarsehat);

        javax.swing.GroupLayout panelkesehatanumumLayout = new javax.swing.GroupLayout(panelkesehatanumum);
        panelkesehatanumum.setLayout(panelkesehatanumumLayout);
        panelkesehatanumumLayout.setHorizontalGroup(
            panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UMUR, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                        .addComponent(GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addGroup(panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                            .addComponent(tombolsehat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jLabel18))
                    .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        panelkesehatanumumLayout.setVerticalGroup(
            panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addGroup(panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17))
                    .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(UMUR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(tombolsehat))
                .addGroup(panelkesehatanumumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel14))
                    .addGroup(panelkesehatanumumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        menuutama.add(panelkesehatanumum, "card7");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setText("CEK AKTIVITAS FISIK");

        jLabel20.setText("Berapa tinggi badan(dalam satuan meter) /berat badan anda?");

        jLabel21.setText("apakah anda sudah olahraga hari ini?");

        inputtinggibadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputtinggibadanActionPerformed(evt);
            }
        });

        inputberatbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputberatbadanActionPerformed(evt);
            }
        });

        jLabel22.setText("Goal berat badan ideal anda adalah :");

        belumolahraga.setText("Belum");
        belumolahraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belumolahragaActionPerformed(evt);
            }
        });

        sudaholahraga.setText("Sudah");
        sudaholahraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sudaholahragaActionPerformed(evt);
            }
        });

        jLabel23.setText("Saran aktivitas yang untuk anda");

        saranaktivitas.setColumns(20);
        saranaktivitas.setRows(5);
        jScrollPane3.setViewportView(saranaktivitas);

        tombolok.setText("OK");
        tombolok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolokMouseClicked(evt);
            }
        });

        hasilperhitunganbbideal.setText(" ");

        javax.swing.GroupLayout panelaktivitasfisikLayout = new javax.swing.GroupLayout(panelaktivitasfisik);
        panelaktivitasfisik.setLayout(panelaktivitasfisikLayout);
        panelaktivitasfisikLayout.setHorizontalGroup(
            panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaktivitasfisikLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addGroup(panelaktivitasfisikLayout.createSequentialGroup()
                        .addComponent(belumolahraga)
                        .addGap(37, 37, 37)
                        .addComponent(sudaholahraga))
                    .addGroup(panelaktivitasfisikLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(hasilperhitunganbbideal))
                    .addComponent(jLabel21)
                    .addGroup(panelaktivitasfisikLayout.createSequentialGroup()
                        .addGroup(panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelaktivitasfisikLayout.createSequentialGroup()
                                .addComponent(inputtinggibadan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputberatbadan))
                            .addGroup(panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolok)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        panelaktivitasfisikLayout.setVerticalGroup(
            panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaktivitasfisikLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(36, 36, 36)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputtinggibadan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(tombolok)
                    .addComponent(inputberatbadan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(hasilperhitunganbbideal))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelaktivitasfisikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(belumolahraga)
                    .addComponent(sudaholahraga))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        menuutama.add(panelaktivitasfisik, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        home.setBackground(new Color(255, 118, 117));
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        // TODO add your handling code here:
        home.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_homeMouseReleased

    private void cekaktivitasfisikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekaktivitasfisikMouseEntered
        // TODO add your handling code here:
        cekaktivitasfisik.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekaktivitasfisikMouseEntered

    private void cekaktivitasfisikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekaktivitasfisikMouseExited
        // TODO add your handling code here:
        cekaktivitasfisik.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_cekaktivitasfisikMouseExited

    private void cekaktivitasfisikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekaktivitasfisikMousePressed
        // TODO add your handling code here:
        cekaktivitasfisik.setBackground(new Color(255, 118, 117));
    }//GEN-LAST:event_cekaktivitasfisikMousePressed

    private void cekaktivitasfisikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekaktivitasfisikMouseReleased
        // TODO add your handling code here:
        cekaktivitasfisik.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekaktivitasfisikMouseReleased

    private void cekpolamakanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolamakanMouseEntered
        // TODO add your handling code here:
        cekpolamakan.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekpolamakanMouseEntered

    private void cekpolamakanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolamakanMouseExited
        // TODO add your handling code here:
        cekpolamakan.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_cekpolamakanMouseExited

    private void cekpolamakanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolamakanMousePressed
        // TODO add your handling code here:
        cekpolamakan.setBackground(new Color(255, 118, 117));
    }//GEN-LAST:event_cekpolamakanMousePressed

    private void cekpolamakanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolamakanMouseReleased
        // TODO add your handling code here:
        cekpolamakan.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekpolamakanMouseReleased

    private void cekpolatidurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolatidurMouseEntered
        // TODO add your handling code here:
        cekpolatidur.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekpolatidurMouseEntered

    private void cekpolatidurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolatidurMouseExited
        // TODO add your handling code here:
        cekpolatidur.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_cekpolatidurMouseExited

    private void cekpolatidurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolatidurMousePressed
        // TODO add your handling code here:
        cekpolatidur.setBackground(new Color(255, 118, 117));
    }//GEN-LAST:event_cekpolatidurMousePressed

    private void cekpolatidurMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolatidurMouseReleased
        // TODO add your handling code here:
        cekpolatidur.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekpolatidurMouseReleased

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(255, 118, 117));
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseReleased
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_jPanel8MouseReleased

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        menuutama.removeAll();
        menuutama.repaint();
        menuutama.revalidate();
        menuutama.add(panelkesehatanumum);
        menuutama.repaint();
        menuutama.revalidate();
    }//GEN-LAST:event_homeMouseClicked

    private void cekaktivitasfisikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekaktivitasfisikMouseClicked
        // TODO add your handling code here:
        menuutama.removeAll();
        menuutama.repaint();
        menuutama.revalidate();
        menuutama.add(panelaktivitasfisik);
        menuutama.repaint();
        menuutama.revalidate();
    }//GEN-LAST:event_cekaktivitasfisikMouseClicked

    private void cekpolamakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolamakanMouseClicked
        // TODO add your handling code here:
        menuutama.removeAll();
        menuutama.repaint();
        menuutama.revalidate();
        menuutama.add(panelpolamakan);
        menuutama.repaint();
        menuutama.revalidate();
    }//GEN-LAST:event_cekpolamakanMouseClicked

    private void cekpolatidurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekpolatidurMouseClicked
        // TODO add your handling code here:
        menuutama.removeAll();
        menuutama.repaint();
        menuutama.revalidate();
        menuutama.add(panelpolatidur);
        menuutama.repaint();
        menuutama.revalidate();
    }//GEN-LAST:event_cekpolatidurMouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "apakah anda yakin ingin keluar?");
        this.setVisible(false);
        if (dialogResult == 0) {
            Login n = new Login();
            n.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        komentarsehat.setText("jika sakit yang anda alami merupakan penyakit serius saya sarankan untuk \n"
                + "segera konsultasi ke dokter. jika rasa sakit yang anda alami tidak serius/\n"
                + "parah, saya sarankan untuk mencoba aplikasi kami. anda akan mendapatkan \n"
                + "saran mengenai apa yang harus anda lakukan atau konsumsi.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cekkesehatanumumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekkesehatanumumMouseClicked
        // TODO add your handling code here:
        menuutama.removeAll();
        menuutama.repaint();
        menuutama.revalidate();
        menuutama.add(panelumum);
        menuutama.repaint();
        menuutama.revalidate();
    }//GEN-LAST:event_cekkesehatanumumMouseClicked

    private void cekkesehatanumumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekkesehatanumumMouseEntered
        // TODO add your handling code here:
        cekkesehatanumum.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekkesehatanumumMouseEntered

    private void cekkesehatanumumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekkesehatanumumMouseExited
        // TODO add your handling code here:
        cekkesehatanumum.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_cekkesehatanumumMouseExited

    private void cekkesehatanumumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekkesehatanumumMousePressed
        // TODO add your handling code here:
        cekkesehatanumum.setBackground(new Color(255, 118, 117));
    }//GEN-LAST:event_cekkesehatanumumMousePressed

    private void cekkesehatanumumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekkesehatanumumMouseReleased
        // TODO add your handling code here:
        cekkesehatanumum.setBackground(new Color(250, 177, 160));
    }//GEN-LAST:event_cekkesehatanumumMouseReleased
    int umur;
    public static String gender;
    private void GENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENDERActionPerformed
        // TODO add your handling code here:
        if (GENDER.getText().equals("LAKI-LAKI")) {
            gender = GENDER.getText();
        } else if (GENDER.getText().equals("PEREMPUAN")) {
            gender = GENDER.getText();
        }
    }//GEN-LAST:event_GENDERActionPerformed
String keterangan;
    private void UMURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMURActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UMURActionPerformed

    private void tombolsehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsehatActionPerformed
        // TODO add your handling code here:
        umur = Integer.parseInt(UMUR.getText());
        if ((umur > 0)&&(umur < 12) && (GENDER.getText().equals("LAKI-LAKI"))) {
            komentarsehat.setText("anda adalah anak laki-laki dibawah umur");
        } else if ((umur > 0) && (umur < 12) && (GENDER.getText().equals("PEREMPUAN"))) {
            komentarsehat.setText("anda adalah anak perempuan dibawah umur");
        } else if ((umur > 13) && (umur < 20) && (GENDER.getText().equals("LAKI-LAKI"))) {
            komentarsehat.setText("anda adalah anak remaja laki-laki");
        } else if ((umur > 13) && (umur < 20) && (GENDER.getText().equals("PEREMPUAN"))) {
            komentarsehat.setText("anda adalah orang remaja perempuan");
        } else if ((umur > 20) && (umur < 50) && (GENDER.getText().equals("PEREMPUAN"))) {
            komentarsehat.setText("anda adalah orang dewasa perempuan");
        } else if ((umur > 20) && (umur < 50) && (GENDER.getText().equals("LAKI-LAKI"))) {
            komentarsehat.setText("anda adalah orang dewasa laki-laki");
        } else if ((umur > 50) && (GENDER.getText().equals("PEREMPUAN"))) {
            komentarsehat.setText("anda adalah lansia perempuan");
        } else if ((umur > 50) && (GENDER.getText().equals("PEREMPUAN"))) {
            komentarsehat.setText("anda adalah lansia laki-laki");
        }
    }//GEN-LAST:event_tombolsehatActionPerformed

    private void belumolahragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belumolahragaActionPerformed
        // TODO add your handling code here:
        saranaktivitas.setText("saya sarankan anda untuk berolahraga, selain baik untuk tubuh anda\n" + "berolahraga juga dapat meredakan stress");
    }//GEN-LAST:event_belumolahragaActionPerformed
    String meter;
    int tinggi = 0, berat = 0;
    double bmi = 0;
    String info;
    private void inputtinggibadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputtinggibadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputtinggibadanActionPerformed

    private void inputberatbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputberatbadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputberatbadanActionPerformed
double Tinggi;
    private void tombolokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolokMouseClicked
        // TODO add your handling code here:
        tinggi = Integer.parseInt(inputtinggibadan.getText());
        berat = Integer.parseInt(inputberatbadan.getText());
        Tinggi = (tinggi+tinggi)/100;
        bmi = berat / Tinggi ;
        if (bmi < 18){
            info = "Berat badan anda belum ideal, kekurangan berat badan";
    }   else if ((bmi > 18)&&(bmi < 22)){
            info = "Berat badan anda sudah ideal";
    }   else if ((bmi > 22)){
            info = "Berat badan anda belum ideal, kelebihan berat badan";
    }
        hasilperhitunganbbideal.setText(info);
    }//GEN-LAST:event_tombolokMouseClicked

    private void berapamakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berapamakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berapamakanActionPerformed

    private void makanankarboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanankarboActionPerformed
        // TODO add your handling code here:
        switch(makanankarbo.getSelectedIndex()){
            case 0:
            sarankonsumsi.setText("");
            break;
            case 1:
            sarankonsumsi.setText("untuk rekomendasi takaran biasanya berkisar antara 1/2 hingga 1\n" + "cangkir beras matang per porsi untuk makanan utama");
            break;
            case 2:
            sarankonsumsi.setText("dalam satu hidangan mie bisa berkisar antara 1/2 hingga 1 cup\n" + "(sekitar 50-100 gram)");
            break;
            case 3:
            sarankonsumsi.setText("Kementerian Kesehatan Indonesia merekomendasikan konsumsi 300-400 \n" + "gram sayuran per hari, termasuk kentang, dalam makanan sehari-hari.");
            break;
            case 4:
            sarankonsumsi.setText("disarankan untuk mengonsumsi sekitar 6-8 ons (sekitar 170-230 gram)" );
            break;
            case 5:
            sarankonsumsi.setText("disarankan untuk mengonsumsi sekitar 1/2 hingga 1 cangkir biji \n" + "jagung matang per hari");
            break;
        }
    }//GEN-LAST:event_makanankarboActionPerformed

    private void makananproteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makananproteinActionPerformed
        // TODO add your handling code here:
        switch(makananprotein.getSelectedIndex()){
            case 0:
            sarankonsumsi.setText("");
            break;
            case 1:
            sarankonsumsi.setText("dalam 100 gram daging sapi panggang, biasanya terdapat sekitar 26 gram\n" + "protein. sementara itu kebutuhan protein adalah sekitar 0,8\n"+"gram protein per kilogram berat badan per hari");
            break;
            case 2:
            sarankonsumsi.setText("Sebuah telur rata-rata mengandung sekitar 6-7 gram protein\n" + " rekomendasi asupan protein harian untuk orang dewasa berkisar antara 46-56 gram per hari");
            break;
            case 3:
            sarankonsumsi.setText("Tempe mengandung Sekitar 19-20 gram protein per 100 gram \n" + "tinggal menyesuaikan dengan kebutuhan protein anda dengan mengalikan berat badan dengan 0,8");
            break;
            case 4:
            sarankonsumsi.setText("disarankan untuk mengonsumsi sekitar 6-8 ons (sekitar 170-230 gram)" );
            break;
            case 5:
            sarankonsumsi.setText("disarankan untuk mengonsumsi sekitar 1/2 hingga 1 cangkir biji \n" + "jagung matang per hari");
            break;
        }
    }//GEN-LAST:event_makananproteinActionPerformed

    private void awaltidurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awaltidurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awaltidurActionPerformed
int jamawalTidur, jamawalBangun, menitAwalbangun, menitAwaltidur;
long hours, minutes;
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jamawalTidur = Integer.parseInt(awaltidur.getText());
        menitAwaltidur = Integer.parseInt(menitawaltidur.getText());
        jamawalBangun = Integer.parseInt(awalbangun.getText());
        menitAwalbangun = Integer.parseInt(menitawalbangun.getText());

        LocalTime jamTidur = LocalTime.of(jamawalTidur, menitAwaltidur);
        LocalTime jamBangun = LocalTime.of(jamawalBangun, menitAwalbangun);

        Duration duration = Duration.between(jamBangun, jamTidur);

        hours = duration.toHours();
        minutes = duration.toMinutesPart();
        hasilkurang.setText(hours+":"+minutes);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void menitawaltidurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menitawaltidurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menitawaltidurActionPerformed

    private void menitawalbangunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menitawalbangunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menitawalbangunActionPerformed

    private void tidursiangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidursiangActionPerformed
        // TODO add your handling code here:
        komentartidur.setText("anda telah tidur selama "+hours+" jam dan anda telah tidur siang.\n" 
                    +"anda telah memiliki siklus tidur yang baik, pertahankan");
    }//GEN-LAST:event_tidursiangActionPerformed

    private void tidaktidursiangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidaktidursiangActionPerformed
        // TODO add your handling code here:
        komentartidur.setText("anda telah tidur selama "+hours+" jam namun anda tidak tidur siang.\n" 
                +"saya sarankan anda untuk tidur siang, karena dengan tidur siang yang baik,\n"
                +"anda akan dapat memperkuat ingatan dan meningkatkan konsentrasi.");
    }//GEN-LAST:event_tidaktidursiangActionPerformed

    private void tombolcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcaraActionPerformed
        // TODO add your handling code here:
        caramenghitung.setText("letakkan 2 jari (telunjuk dan tengah) untuk meraba pergelangan tangan\n"
                + "letakkan tepat ditengah sampai merasakan denyutnya. hitung berapa kali per menit\n"
                + "nadimu berdenyut");
    }//GEN-LAST:event_tombolcaraActionPerformed
int Nadi;
    private void okenadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okenadiActionPerformed
        // TODO add your handling code here:
        Nadi = Integer.parseInt(nadi.getText());
        if (Nadi < 90){
            info = "Denyut nadi anda terlalu rendah";
    }   else if ((Nadi > 90)&&(Nadi < 110)){
            info = "Denyut nadi anda sudah normal";
    }   else if ((Nadi > 110)){
            info = "Denyut nadi anda terlalu tinggi";
    }
        caramenghitung.setText(info);
    }//GEN-LAST:event_okenadiActionPerformed
int Makan;
String infomakan;
    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        Makan = Integer.parseInt(berapamakan.getText());
        if (Makan <= 2){
            infomakan = "Anda tidak cukup mendapatkan asupan energi dalam sehari\n" + "sehingga berpotensi terkena maag";
    }   else if ((Makan > 2)&&(Makan <= 5)){
            infomakan = "Anda telah cukup mendapatkan asupan energi dalam sehari";
    }   else if ((Makan > 5)){
            infomakan = "Anda terlalu banyak mendapatkan asupan energi dalam sehari\n" + "sehingga memberatkan kerja lambung";
    }
        sarankonsumsi.setText(infomakan);
    }//GEN-LAST:event_OkActionPerformed

    private void sudaholahragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sudaholahragaActionPerformed
        // TODO add your handling code here:
        saranaktivitas.setText("Anda telah berolahraga, selain baik untuk jantung anda\n" + "berolahraga juga dapat meredakan stress");
    }//GEN-LAST:event_sudaholahragaActionPerformed

    private void makananvitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makananvitActionPerformed
        // TODO add your handling code here:
        switch(makananvit.getSelectedIndex()){
            case 0:
            sarankonsumsi.setText("");
            break;
            case 1:
            sarankonsumsi.setText("Jeruk: Kaya akan vitamin C.");
            break;
            case 2:
            sarankonsumsi.setText("Alpukat: Mengandung vitamin E dan K.");
            break;
            case 3:
            sarankonsumsi.setText("Pisang: Mengandung vitamin B6 dan C.");
            break;
            case 4:
            sarankonsumsi.setText("Kiwi: Kaya akan vitamin C dan K." );
            break;
            case 5:
            sarankonsumsi.setText("Bayam: Mengandung vitamin A, C, dan K.");
            break;
            case 6:
            sarankonsumsi.setText("Brokoli: Kaya akan vitamin C dan K.");
            break;
            case 7:
            sarankonsumsi.setText("Wortel: Mengandung vitamin A.");
            break;
            case 8:
            sarankonsumsi.setText("Tomat: Mengandung vitamin C dan A.");
            break;
            case 9:
            sarankonsumsi.setText("Kacang almond: Mengandung vitamin E.");
            break;
            case 10:
            sarankonsumsi.setText("Kacang-kacangan: Mengandung vitamin B kompleks, seperti B6 dan asam folat.");
            break;
            case 11:
            sarankonsumsi.setText("Biji bunga matahari: Mengandung vitamin E.");
            break;
            case 12:
            sarankonsumsi.setText("Susu: Mengandung vitamin D dan B12.");
            break;
            case 13:
            sarankonsumsi.setText("Yogurt: Mengandung vitamin B12 dan D.");
            break;
            case 14:
            sarankonsumsi.setText("Keju: Mengandung vitamin A dan B12.");
            break;
            case 15:
            sarankonsumsi.setText("Salmon: Kaya akan vitamin D dan B12.");
            break;
            case 16:
            sarankonsumsi.setText("Sarden: Mengandung vitamin D dan B12.");
            break;
            case 17:
            sarankonsumsi.setText("Teh hijau: Mengandung vitamin K.");
            break;
        }
    }//GEN-LAST:event_makananvitActionPerformed
double Kebutuhanprotein;
String Kebutuhanproteinstring;
    private void kebutuhanproteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebutuhanproteinActionPerformed
        // TODO add your handling code here:
        Kebutuhanprotein = berat*8/10;
        Kebutuhanproteinstring = Double.toString(Kebutuhanprotein);
        protein.setText(Kebutuhanproteinstring);
    }//GEN-LAST:event_kebutuhanproteinActionPerformed

    private void sakittenggorokanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakittenggorokanActionPerformed
        // TODO add your handling code here:
        kondisi.setText("Minumlah air putih dalam jumlah yang cukup, Istirahat, bila perlu\n" + "berkumur dengan larutan air hangat dan garam");
    }//GEN-LAST:event_sakittenggorokanActionPerformed

    private void hidungtersumbatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidungtersumbatActionPerformed
        // TODO add your handling code here:
        kondisi.setText("Semprotan atau tetes hidung dengan larutan salin (garam) dapat membantu\n" + "membersihkan dan melembutkan lendir di hidung, membantu Anda bernapas lebih mudah.");
    }//GEN-LAST:event_hidungtersumbatActionPerformed

    private void nyeriototActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyeriototActionPerformed
        // TODO add your handling code here:
        kondisi.setText("Kompres dingin dapat mengurangi peradangan dan pembengkakan, sementara\n" + "kompres panas dapat membantu meningkatkan aliran darah ke area yang terkena.");
    }//GEN-LAST:event_nyeriototActionPerformed

    private void sakitkepalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakitkepalaActionPerformed
        // TODO add your handling code here:
        kondisi.setText("Pijatan ringan pada area leher, bahu, atau kepala, serta kompres dingin \n" + "atau hangat pada area yang terasa nyeri dapat membantu mengurangi ketegangan\n" + "dan meredakan sakit kepala.");
    }//GEN-LAST:event_sakitkepalaActionPerformed

    private void sehatwalafiatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehatwalafiatActionPerformed
        // TODO add your handling code here:
        kondisi.setText("Alhamdulillah, semoga anda sehat selalu");
    }//GEN-LAST:event_sehatwalafiatActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GENDER;
    private javax.swing.JButton Ok;
    private javax.swing.JTextField UMUR;
    private javax.swing.JTextField awalbangun;
    private javax.swing.JTextField awaltidur;
    private javax.swing.JButton belumolahraga;
    private javax.swing.JTextField berapamakan;
    private javax.swing.JTextArea caramenghitung;
    private javax.swing.JPanel cekaktivitasfisik;
    private javax.swing.JPanel cekkesehatanumum;
    private javax.swing.JPanel cekpolamakan;
    private javax.swing.JPanel cekpolatidur;
    private javax.swing.JTextField hasilkurang;
    private javax.swing.JLabel hasilperhitunganbbideal;
    private javax.swing.JButton hidungtersumbat;
    private javax.swing.JPanel home;
    private javax.swing.JTextField inputberatbadan;
    private javax.swing.JTextField inputtinggibadan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kebutuhanprotein;
    private javax.swing.JTextArea komentarsehat;
    private javax.swing.JTextArea komentartidur;
    private javax.swing.JTextArea kondisi;
    private javax.swing.JComboBox<String> makanankarbo;
    private javax.swing.JComboBox<String> makananprotein;
    private javax.swing.JComboBox<String> makananvit;
    private javax.swing.JTextField menitawalbangun;
    private javax.swing.JTextField menitawaltidur;
    private javax.swing.JPanel menupanel;
    private javax.swing.JPanel menuutama;
    private javax.swing.JTextField nadi;
    private javax.swing.JButton nyeriotot;
    private javax.swing.JButton okenadi;
    private javax.swing.JPanel panelaktivitasfisik;
    private javax.swing.JPanel panelkesehatanumum;
    private javax.swing.JPanel panelpolamakan;
    private javax.swing.JPanel panelpolatidur;
    private javax.swing.JPanel panelumum;
    private javax.swing.JTextField protein;
    private javax.swing.JButton sakitkepala;
    private javax.swing.JButton sakittenggorokan;
    private javax.swing.JTextArea saranaktivitas;
    private javax.swing.JTextArea sarankonsumsi;
    private javax.swing.JButton sehatwalafiat;
    private javax.swing.JButton sudaholahraga;
    private javax.swing.JButton tidaktidursiang;
    private javax.swing.JButton tidursiang;
    private javax.swing.JButton tombolcara;
    private javax.swing.JButton tombolok;
    private javax.swing.JButton tombolsehat;
    // End of variables declaration//GEN-END:variables
}
